version: '3'
services:
    database:
        image: ${DATABASE_IMAGE}
        container_name: ${DATABASE_CONTAINER_NAME}
        restart: always
        ports:
            - '${DATABASE_PORT}:3306'
        volumes:
            - ./mysql/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
            MYSQL_DATABASE: ${DATABASE_NAME}
            MYSQL_ROOT_HOST: '%'
networks:
    default:
        external:
            name: main
